# Generated by Django 4.2 on 2024-07-12 14:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("plan", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="plan",
            table="plan",
        ),
    ]
